services:
  web-server:
    image: sthomasch/ishlearn
    restart: unless-stopped
    ports:
      - '80:80' # Map local PORT 80 to docker port 80
    environment: # Configure ENV
      PORT: 80
      REDIS_URL: 'redis:6379' # not present for ARM architecture
      S3_ENDPOINT: 's3server:8000'
    env_file: .prod.env
    depends_on:
      - s3server
  s3server:
    image: scality/s3server
    restart: unless-stopped
    ports:
      - '8000:8000'
    env_file: .prod.env
